## httproute
# httproute:
#   enabled: true
#   domain: nginx.k8s.lan

## stakater application chart
# https://github.com/stakater/application/blob/main/application/values.yaml
# https://github.com/stakater/application/blob/main/application/values-test.yaml
nameOverride: "nginx"
configMap:
  enabled: true
  files:
    config: 
      default.conf: |
        server {
          listen 8080;
          server_name _;
          location / {
            root /usr/share/nginx/html;
            index hello.html;
          }
        }
    html:
      hello.html: |
        <html>
          <body>
            <h1>Hello, World!</h1>
          </body>
        </html>

deployment:
  image:
    repository: "nginx"
    # tag: "1.23.0"
    pullPolicy: IfNotPresent
  replicas: 2
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 101
  securityContext:
    fsGroup: 101
  volumeMounts:
    nginx-cache:
      mountPath: /var/cache/nginx
    nginx-conf:
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
    nginx-html:
      mountPath: /usr/share/nginx/html/hello.html
      subPath: hello.html
    nginx-run:
      mountPath: /var/run
  volumes:
    nginx-cache:
      emptyDir: {}
    nginx-conf:
      configMap:
        name: nginx-config
    nginx-html:
      configMap:
        name: nginx-html
    nginx-run:
      emptyDir: {}
  ports:
    - containerPort: 8080
      name: http
      protocol: TCP
service:
  type: ClusterIP
  port: 8080
networkPolicy:
  enabled: true
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0